apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  labels:
    app: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs-app
        image: doriancanville/nodejs-exemple:1.0
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: postgresql
        - name:  DB_USERNAME
          value: postgres
        - name: DB_PASSWORD
          value: admin
        - name: DB_DATABASE
          value: postgres
        - name: DB_DAILECT
          value: postgres
        - name: DB_PORT
          value: "5432" 
        - name: ACCESS_TOKEN_SECRET
          value: YOUR_SECRET_KEY
        - name: REFRESH_TOKEN_SECRET
          value: YOUR_SECRET_KEY
        - name: ACCESS_TOKEN_EXPIRY
          value: 15m
        - name: REFRESH_TOKEN_EXPIRY
          value: 7d
        - name: REFRESH_TOKEN_COOKIE_NAME
          value: jid
       