apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app: postgresql
Kubernetes/nodejs/nodejs-deployment.ymlspec:
  selector:
    app: postgresql
  ports:
  - name: postgresql
    port: 5432
    targetPort: 5432
  type: ClusterIP
